### ISSUE TITLE
Exception in Icons View on Java 9 code branch

### ISSUE THREAD

**Issue by ricemery** [ricemery/FileChooserFx#13]
This hack needs to be removed from IconsFilesView -
               // HACK!! Force repaint of GridView. The GridView was
               // not repainting when file filter was changed on a huge directory.
               ((GridViewSkin)gridView.getSkin()).updateGridViewItems();

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.chainstaysoftware.filechooser.IconsFilesView$SelectCurrentService$SelectTask.lambda$call$0(IconsFilesView.java:168)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Exception in thread "JavaFX Application Thread" java.lang.reflect.InaccessibleObjectException: Unable to make field private final javafx.scene.control.skin.VirtualFlow javafx.scene.control.skin.VirtualContainerBase.flow accessible: module javafx.controls does not "opens javafx.scene.control.skin" to unnamed module @70811f5c
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
	at impl.org.controlsfx.ReflectionUtils.getVirtualFlow(ReflectionUtils.java:158)
	at impl.org.controlsfx.skin.GridViewSkin.<init>(GridViewSkin.java:52)
	at org.controlsfx.control.GridView.createDefaultSkin(GridView.java:142)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)

**Comment by ricemery** [comment]
There are two issues in play.
The first is the NullPointer in the IconsFileView.

The second is the InaccessiableObjectException. This one looks to be a bug in ControlsFx -  https://bitbucket.org/controlsfx/controlsfx/issues/780/controlsfx-should-support-java-9 .

**Comment by ricemery** [comment]
The IconsView can be re-enabled if the following is passed on the command line when running "--add-opens=javafx.controls/javafx.scene.control.skin=ALL-UNNAMED"

**Comment by ricemery** [comment]
fixed on Java 11 branch..
